"""migrate

Revision ID: 6c3783e32112
Revises: 
Create Date: 2020-02-20 13:22:28.488682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3783e32112'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blogs', 'person', ['users_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.drop_column('blogs', 'users_id')
    # ### end Alembic commands ###
