"""CC

Revision ID: 758ec08842a6
Revises: 2fa36eb6ce25
Create Date: 2020-02-20 11:47:35.808760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758ec08842a6'
down_revision = '2fa36eb6ce25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'posted')
    # ### end Alembic commands ###
