"""achieve migrations

Revision ID: b352aa7f2736
Revises: 0a5c9c54f679
Create Date: 2020-02-20 16:25:42.909638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b352aa7f2736'
down_revision = '0a5c9c54f679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qoutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blogs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('blogs_users_id_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'person', ['user_id'], ['id'])
    op.drop_column('blogs', 'users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_users_id_fkey', 'blogs', 'person', ['users_id'], ['id'])
    op.drop_column('blogs', 'user_id')
    op.drop_table('qoutes')
    # ### end Alembic commands ###
