"""DD

Revision ID: f70067f9a638
Revises: 758ec08842a6
Create Date: 2020-02-20 12:42:48.114937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70067f9a638'
down_revision = '758ec08842a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_email'), 'subscriber', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriber_email'), table_name='subscriber')
    op.drop_table('subscriber')
    # ### end Alembic commands ###
